### ISSUE TITLE
Extensions link failing

### ISSUE THREAD

**Issue by cameronwp** [tofutech/fedoramenu#7]
I'm getting a notification saying the `gnome-extensions-app` command is not found. I have the [Gnome extensions](https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/master/subprojects/extensions-app) app installed as a flatpak. This is on F34 with Gnome 40.1.0.

**Comment by kaansenol5** [comment]
Are you sure you installed gnome-extensions-app and not gnome-extensions? You need both.

Run `dnf install gnome-extensions-app`

**Comment by cameronwp** [comment]
Installing `gnome-extensions-app` fixes the issue. I didn't realize that was a requirement for this extension. You might want to include that somewhere in the README.

Side note: what's the difference between `gnome-extensions-app` and the flatpak? It looks like the `gnome-extensions-app` just a CLI command to open the flatpak?

Thanks! Neat extension.
